# main_optimized.tf — generated by finops-s3 skill
# Changes: aws_s3_bucket_lifecycle_configuration blocks added for each
# versioning-enabled bucket that was missing a noncurrent expiry policy.
# Existing resources are unchanged.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "s3-bucket-ow91mn" {
  bucket = "app-assets-prod"

  tags = {
    Name        = "app-assets-prod"
  }
}

resource "aws_s3_bucket_versioning" "s3-bucket-ow91mn" {
  bucket = aws_s3_bucket.s3-bucket-ow91mn.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket" "s3-bucket-r6r0ih" {
  bucket = "app-assets-staging"

  tags = {
    Name        = "app-assets-staging"
  }
}

resource "aws_s3_bucket_versioning" "s3-bucket-r6r0ih" {
  bucket = aws_s3_bucket.s3-bucket-r6r0ih.id

  versioning_configuration {
    status = "Enabled"
  }
}

# ══════════════════════════════════════════════════════════
# ADDED BY FINOPS-S3: Lifecycle policies to expire noncurrent versions
# ══════════════════════════════════════════════════════════

# Lifecycle policy for app-assets-prod (prod)
# Expires noncurrent versions after 90 days, keeps 5 newest
resource "aws_s3_bucket_lifecycle_configuration" "s3-bucket-ow91mn" {
  bucket = aws_s3_bucket.s3-bucket-ow91mn.id

  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"

    noncurrent_version_expiration {
      noncurrent_days           = 90
      newer_noncurrent_versions = 5
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}
